# coding: utf-8

"""
    MTA 6.2 api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 6.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class ApiIssue(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'category': 'str',
        'create_time': 'str',
        'create_user': 'str',
        'description': 'str',
        'effort': 'int',
        'facts': 'ApiFactMap',
        'id': 'int',
        'incidents': 'list[ApiIncident]',
        'labels': 'list[str]',
        'links': 'list[ApiLink]',
        'name': 'str',
        'rule': 'str',
        'ruleset': 'str',
        'update_user': 'str'
    }

    attribute_map = {
        'category': 'category',
        'create_time': 'createTime',
        'create_user': 'createUser',
        'description': 'description',
        'effort': 'effort',
        'facts': 'facts',
        'id': 'id',
        'incidents': 'incidents',
        'labels': 'labels',
        'links': 'links',
        'name': 'name',
        'rule': 'rule',
        'ruleset': 'ruleset',
        'update_user': 'updateUser'
    }

    def __init__(self, category=None, create_time=None, create_user=None, description=None, effort=None, facts=None, id=None, incidents=None, labels=None, links=None, name=None, rule=None, ruleset=None, update_user=None, _configuration=None):  # noqa: E501
        """ApiIssue - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._category = None
        self._create_time = None
        self._create_user = None
        self._description = None
        self._effort = None
        self._facts = None
        self._id = None
        self._incidents = None
        self._labels = None
        self._links = None
        self._name = None
        self._rule = None
        self._ruleset = None
        self._update_user = None
        self.discriminator = None

        self.category = category
        if create_time is not None:
            self.create_time = create_time
        if create_user is not None:
            self.create_user = create_user
        if description is not None:
            self.description = description
        if effort is not None:
            self.effort = effort
        if facts is not None:
            self.facts = facts
        if id is not None:
            self.id = id
        if incidents is not None:
            self.incidents = incidents
        if labels is not None:
            self.labels = labels
        if links is not None:
            self.links = links
        self.name = name
        self.rule = rule
        self.ruleset = ruleset
        if update_user is not None:
            self.update_user = update_user

    @property
    def category(self):
        """Gets the category of this ApiIssue.  # noqa: E501


        :return: The category of this ApiIssue.  # noqa: E501
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category):
        """Sets the category of this ApiIssue.


        :param category: The category of this ApiIssue.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and category is None:
            raise ValueError("Invalid value for `category`, must not be `None`")  # noqa: E501

        self._category = category

    @property
    def create_time(self):
        """Gets the create_time of this ApiIssue.  # noqa: E501


        :return: The create_time of this ApiIssue.  # noqa: E501
        :rtype: str
        """
        return self._create_time

    @create_time.setter
    def create_time(self, create_time):
        """Sets the create_time of this ApiIssue.


        :param create_time: The create_time of this ApiIssue.  # noqa: E501
        :type: str
        """

        self._create_time = create_time

    @property
    def create_user(self):
        """Gets the create_user of this ApiIssue.  # noqa: E501


        :return: The create_user of this ApiIssue.  # noqa: E501
        :rtype: str
        """
        return self._create_user

    @create_user.setter
    def create_user(self, create_user):
        """Sets the create_user of this ApiIssue.


        :param create_user: The create_user of this ApiIssue.  # noqa: E501
        :type: str
        """

        self._create_user = create_user

    @property
    def description(self):
        """Gets the description of this ApiIssue.  # noqa: E501


        :return: The description of this ApiIssue.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ApiIssue.


        :param description: The description of this ApiIssue.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def effort(self):
        """Gets the effort of this ApiIssue.  # noqa: E501


        :return: The effort of this ApiIssue.  # noqa: E501
        :rtype: int
        """
        return self._effort

    @effort.setter
    def effort(self, effort):
        """Sets the effort of this ApiIssue.


        :param effort: The effort of this ApiIssue.  # noqa: E501
        :type: int
        """

        self._effort = effort

    @property
    def facts(self):
        """Gets the facts of this ApiIssue.  # noqa: E501


        :return: The facts of this ApiIssue.  # noqa: E501
        :rtype: ApiFactMap
        """
        return self._facts

    @facts.setter
    def facts(self, facts):
        """Sets the facts of this ApiIssue.


        :param facts: The facts of this ApiIssue.  # noqa: E501
        :type: ApiFactMap
        """

        self._facts = facts

    @property
    def id(self):
        """Gets the id of this ApiIssue.  # noqa: E501


        :return: The id of this ApiIssue.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ApiIssue.


        :param id: The id of this ApiIssue.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def incidents(self):
        """Gets the incidents of this ApiIssue.  # noqa: E501


        :return: The incidents of this ApiIssue.  # noqa: E501
        :rtype: list[ApiIncident]
        """
        return self._incidents

    @incidents.setter
    def incidents(self, incidents):
        """Sets the incidents of this ApiIssue.


        :param incidents: The incidents of this ApiIssue.  # noqa: E501
        :type: list[ApiIncident]
        """

        self._incidents = incidents

    @property
    def labels(self):
        """Gets the labels of this ApiIssue.  # noqa: E501


        :return: The labels of this ApiIssue.  # noqa: E501
        :rtype: list[str]
        """
        return self._labels

    @labels.setter
    def labels(self, labels):
        """Sets the labels of this ApiIssue.


        :param labels: The labels of this ApiIssue.  # noqa: E501
        :type: list[str]
        """

        self._labels = labels

    @property
    def links(self):
        """Gets the links of this ApiIssue.  # noqa: E501


        :return: The links of this ApiIssue.  # noqa: E501
        :rtype: list[ApiLink]
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this ApiIssue.


        :param links: The links of this ApiIssue.  # noqa: E501
        :type: list[ApiLink]
        """

        self._links = links

    @property
    def name(self):
        """Gets the name of this ApiIssue.  # noqa: E501


        :return: The name of this ApiIssue.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ApiIssue.


        :param name: The name of this ApiIssue.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def rule(self):
        """Gets the rule of this ApiIssue.  # noqa: E501


        :return: The rule of this ApiIssue.  # noqa: E501
        :rtype: str
        """
        return self._rule

    @rule.setter
    def rule(self, rule):
        """Sets the rule of this ApiIssue.


        :param rule: The rule of this ApiIssue.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and rule is None:
            raise ValueError("Invalid value for `rule`, must not be `None`")  # noqa: E501

        self._rule = rule

    @property
    def ruleset(self):
        """Gets the ruleset of this ApiIssue.  # noqa: E501


        :return: The ruleset of this ApiIssue.  # noqa: E501
        :rtype: str
        """
        return self._ruleset

    @ruleset.setter
    def ruleset(self, ruleset):
        """Sets the ruleset of this ApiIssue.


        :param ruleset: The ruleset of this ApiIssue.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and ruleset is None:
            raise ValueError("Invalid value for `ruleset`, must not be `None`")  # noqa: E501

        self._ruleset = ruleset

    @property
    def update_user(self):
        """Gets the update_user of this ApiIssue.  # noqa: E501


        :return: The update_user of this ApiIssue.  # noqa: E501
        :rtype: str
        """
        return self._update_user

    @update_user.setter
    def update_user(self, update_user):
        """Sets the update_user of this ApiIssue.


        :param update_user: The update_user of this ApiIssue.  # noqa: E501
        :type: str
        """

        self._update_user = update_user

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiIssue, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiIssue):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ApiIssue):
            return True

        return self.to_dict() != other.to_dict()
