# coding: utf-8

"""
    MTA 6.1 api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 6.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class ApiRuleSet(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'create_time': 'str',
        'create_user': 'str',
        'custom': 'bool',
        'description': 'str',
        'id': 'int',
        'identity': 'ApiRef',
        'image': 'ApiRef',
        'kind': 'str',
        'name': 'str',
        'repository': 'ApiRepository',
        'rules': 'list[ApiRule]',
        'update_user': 'str'
    }

    attribute_map = {
        'create_time': 'createTime',
        'create_user': 'createUser',
        'custom': 'custom',
        'description': 'description',
        'id': 'id',
        'identity': 'identity',
        'image': 'image',
        'kind': 'kind',
        'name': 'name',
        'repository': 'repository',
        'rules': 'rules',
        'update_user': 'updateUser'
    }

    def __init__(self, create_time=None, create_user=None, custom=None, description=None, id=None, identity=None, image=None, kind=None, name=None, repository=None, rules=None, update_user=None, _configuration=None):  # noqa: E501
        """ApiRuleSet - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._create_time = None
        self._create_user = None
        self._custom = None
        self._description = None
        self._id = None
        self._identity = None
        self._image = None
        self._kind = None
        self._name = None
        self._repository = None
        self._rules = None
        self._update_user = None
        self.discriminator = None

        if create_time is not None:
            self.create_time = create_time
        if create_user is not None:
            self.create_user = create_user
        if custom is not None:
            self.custom = custom
        if description is not None:
            self.description = description
        if id is not None:
            self.id = id
        if identity is not None:
            self.identity = identity
        if image is not None:
            self.image = image
        if kind is not None:
            self.kind = kind
        if name is not None:
            self.name = name
        if repository is not None:
            self.repository = repository
        if rules is not None:
            self.rules = rules
        if update_user is not None:
            self.update_user = update_user

    @property
    def create_time(self):
        """Gets the create_time of this ApiRuleSet.  # noqa: E501


        :return: The create_time of this ApiRuleSet.  # noqa: E501
        :rtype: str
        """
        return self._create_time

    @create_time.setter
    def create_time(self, create_time):
        """Sets the create_time of this ApiRuleSet.


        :param create_time: The create_time of this ApiRuleSet.  # noqa: E501
        :type: str
        """

        self._create_time = create_time

    @property
    def create_user(self):
        """Gets the create_user of this ApiRuleSet.  # noqa: E501


        :return: The create_user of this ApiRuleSet.  # noqa: E501
        :rtype: str
        """
        return self._create_user

    @create_user.setter
    def create_user(self, create_user):
        """Sets the create_user of this ApiRuleSet.


        :param create_user: The create_user of this ApiRuleSet.  # noqa: E501
        :type: str
        """

        self._create_user = create_user

    @property
    def custom(self):
        """Gets the custom of this ApiRuleSet.  # noqa: E501


        :return: The custom of this ApiRuleSet.  # noqa: E501
        :rtype: bool
        """
        return self._custom

    @custom.setter
    def custom(self, custom):
        """Sets the custom of this ApiRuleSet.


        :param custom: The custom of this ApiRuleSet.  # noqa: E501
        :type: bool
        """

        self._custom = custom

    @property
    def description(self):
        """Gets the description of this ApiRuleSet.  # noqa: E501


        :return: The description of this ApiRuleSet.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ApiRuleSet.


        :param description: The description of this ApiRuleSet.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def id(self):
        """Gets the id of this ApiRuleSet.  # noqa: E501


        :return: The id of this ApiRuleSet.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ApiRuleSet.


        :param id: The id of this ApiRuleSet.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def identity(self):
        """Gets the identity of this ApiRuleSet.  # noqa: E501


        :return: The identity of this ApiRuleSet.  # noqa: E501
        :rtype: ApiRef
        """
        return self._identity

    @identity.setter
    def identity(self, identity):
        """Sets the identity of this ApiRuleSet.


        :param identity: The identity of this ApiRuleSet.  # noqa: E501
        :type: ApiRef
        """

        self._identity = identity

    @property
    def image(self):
        """Gets the image of this ApiRuleSet.  # noqa: E501


        :return: The image of this ApiRuleSet.  # noqa: E501
        :rtype: ApiRef
        """
        return self._image

    @image.setter
    def image(self, image):
        """Sets the image of this ApiRuleSet.


        :param image: The image of this ApiRuleSet.  # noqa: E501
        :type: ApiRef
        """

        self._image = image

    @property
    def kind(self):
        """Gets the kind of this ApiRuleSet.  # noqa: E501


        :return: The kind of this ApiRuleSet.  # noqa: E501
        :rtype: str
        """
        return self._kind

    @kind.setter
    def kind(self, kind):
        """Sets the kind of this ApiRuleSet.


        :param kind: The kind of this ApiRuleSet.  # noqa: E501
        :type: str
        """

        self._kind = kind

    @property
    def name(self):
        """Gets the name of this ApiRuleSet.  # noqa: E501


        :return: The name of this ApiRuleSet.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ApiRuleSet.


        :param name: The name of this ApiRuleSet.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def repository(self):
        """Gets the repository of this ApiRuleSet.  # noqa: E501


        :return: The repository of this ApiRuleSet.  # noqa: E501
        :rtype: ApiRepository
        """
        return self._repository

    @repository.setter
    def repository(self, repository):
        """Sets the repository of this ApiRuleSet.


        :param repository: The repository of this ApiRuleSet.  # noqa: E501
        :type: ApiRepository
        """

        self._repository = repository

    @property
    def rules(self):
        """Gets the rules of this ApiRuleSet.  # noqa: E501


        :return: The rules of this ApiRuleSet.  # noqa: E501
        :rtype: list[ApiRule]
        """
        return self._rules

    @rules.setter
    def rules(self, rules):
        """Sets the rules of this ApiRuleSet.


        :param rules: The rules of this ApiRuleSet.  # noqa: E501
        :type: list[ApiRule]
        """

        self._rules = rules

    @property
    def update_user(self):
        """Gets the update_user of this ApiRuleSet.  # noqa: E501


        :return: The update_user of this ApiRuleSet.  # noqa: E501
        :rtype: str
        """
        return self._update_user

    @update_user.setter
    def update_user(self, update_user):
        """Sets the update_user of this ApiRuleSet.


        :param update_user: The update_user of this ApiRuleSet.  # noqa: E501
        :type: str
        """

        self._update_user = update_user

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiRuleSet, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiRuleSet):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ApiRuleSet):
            return True

        return self.to_dict() != other.to_dict()
