# coding: utf-8

"""
    MTA 6.1 api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 6.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class MigrationwavesApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def migrationwaves_get(self, **kwargs):  # noqa: E501
        """List all migration waves.  # noqa: E501

        List all migration waves.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.migrationwaves_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[ApiMigrationWave]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.migrationwaves_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.migrationwaves_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def migrationwaves_get_with_http_info(self, **kwargs):  # noqa: E501
        """List all migration waves.  # noqa: E501

        List all migration waves.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.migrationwaves_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[ApiMigrationWave]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method migrationwaves_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['bearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/migrationwaves', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[ApiMigrationWave]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def migrationwaves_id_delete(self, id, **kwargs):  # noqa: E501
        """Delete a migration wave.  # noqa: E501

        Delete a migration wave.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.migrationwaves_id_delete(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: MigrationWave id (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.migrationwaves_id_delete_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.migrationwaves_id_delete_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def migrationwaves_id_delete_with_http_info(self, id, **kwargs):  # noqa: E501
        """Delete a migration wave.  # noqa: E501

        Delete a migration wave.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.migrationwaves_id_delete_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: MigrationWave id (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method migrationwaves_id_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if self.api_client.client_side_validation and ('id' not in params or
                                                       params['id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `id` when calling `migrationwaves_id_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = ['bearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/migrationwaves/{id}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def migrationwaves_id_get(self, id, **kwargs):  # noqa: E501
        """Get a migration wave by ID.  # noqa: E501

        Get a migration wave by ID.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.migrationwaves_id_get(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: Migration Wave ID (required)
        :return: ApiMigrationWave
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.migrationwaves_id_get_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.migrationwaves_id_get_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def migrationwaves_id_get_with_http_info(self, id, **kwargs):  # noqa: E501
        """Get a migration wave by ID.  # noqa: E501

        Get a migration wave by ID.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.migrationwaves_id_get_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: Migration Wave ID (required)
        :return: ApiMigrationWave
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method migrationwaves_id_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if self.api_client.client_side_validation and ('id' not in params or
                                                       params['id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `id` when calling `migrationwaves_id_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['bearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/migrationwaves/{id}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ApiMigrationWave',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def migrationwaves_id_put(self, id, migration_wave, **kwargs):  # noqa: E501
        """Update a migration wave.  # noqa: E501

        Update a migration wave.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.migrationwaves_id_put(id, migration_wave, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: MigrationWave id (required)
        :param ApiMigrationWave migration_wave: MigrationWave data (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.migrationwaves_id_put_with_http_info(id, migration_wave, **kwargs)  # noqa: E501
        else:
            (data) = self.migrationwaves_id_put_with_http_info(id, migration_wave, **kwargs)  # noqa: E501
            return data

    def migrationwaves_id_put_with_http_info(self, id, migration_wave, **kwargs):  # noqa: E501
        """Update a migration wave.  # noqa: E501

        Update a migration wave.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.migrationwaves_id_put_with_http_info(id, migration_wave, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: MigrationWave id (required)
        :param ApiMigrationWave migration_wave: MigrationWave data (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'migration_wave']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method migrationwaves_id_put" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if self.api_client.client_side_validation and ('id' not in params or
                                                       params['id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `id` when calling `migrationwaves_id_put`")  # noqa: E501
        # verify the required parameter 'migration_wave' is set
        if self.api_client.client_side_validation and ('migration_wave' not in params or
                                                       params['migration_wave'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `migration_wave` when calling `migrationwaves_id_put`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'migration_wave' in params:
            body_params = params['migration_wave']
        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['bearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/migrationwaves/{id}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def migrationwaves_post(self, migrationwave, **kwargs):  # noqa: E501
        """Create a migration wave.  # noqa: E501

        Create a migration wave.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.migrationwaves_post(migrationwave, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ApiMigrationWave migrationwave: Migration Wave data (required)
        :return: ApiMigrationWave
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.migrationwaves_post_with_http_info(migrationwave, **kwargs)  # noqa: E501
        else:
            (data) = self.migrationwaves_post_with_http_info(migrationwave, **kwargs)  # noqa: E501
            return data

    def migrationwaves_post_with_http_info(self, migrationwave, **kwargs):  # noqa: E501
        """Create a migration wave.  # noqa: E501

        Create a migration wave.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.migrationwaves_post_with_http_info(migrationwave, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ApiMigrationWave migrationwave: Migration Wave data (required)
        :return: ApiMigrationWave
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['migrationwave']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method migrationwaves_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'migrationwave' is set
        if self.api_client.client_side_validation and ('migrationwave' not in params or
                                                       params['migrationwave'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `migrationwave` when calling `migrationwaves_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'migrationwave' in params:
            body_params = params['migrationwave']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['bearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/migrationwaves', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ApiMigrationWave',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
